name: flipart
description: FlipArt is an App to create some animation, like a FlipBook
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_colorpicker: 0.2.6

flutter:
  uses-material-design: true
